<Main3>:
    BoxLayout:
        orientation: 'vertical'
        padding: 20

        Label:
            text: "Tela 3"
            font_size: 32

        Label:
            id: moeda1
            text: "Dólar: Aguarde"

        Label:
            id: moeda2
            text: "Euro: Aguarde"

        Label:
            id: moeda3
            text: "Bitcoin: Aguarde"

        Button:
            text: "Formulário"
            on_release: app.switch_screen("main1", "right")
