<Main2>:
    BoxLayout:
        orientation: 'vertical'
        padding: 20

        Label:
            text: "Tela 2"
            font_size: 32
        Label:
            id: moeda1
            text: "Dolar: Aguarde"
        Label:
            id: moeda2
            text: "Euro: Aguarde"
        Label:
            id: moeda3
            text: "Bitcoin: Aguarde"
        Button:
            text: "Voltar para Tela 1"
            on_release: app.switch_screen("main1", "right")

